name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Atualizado para v3
      - name: Install dependencies
        run: npm install  # Instala as dependências NPM
      - name: Cypress run
        uses: cypress-io/github-action@v3  # Atualizado para v3
        with:
          start: npm start  # Comando para iniciar sua aplicação, se necessário
