name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Atualizado para v3
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Configura o Node.js
        with:
          node-version: '16'  # Ou a versão que você preferir
      - name: Install NPM dependencies
        run: npm ci  # Instala as dependências
      - name: Start server
        run: npm start &  # Inicia o servidor em segundo plano
        env:
          CI: true  # Define o ambiente de CI
      - name: Cypress run
        uses: cypress-io/github-action@v3  # Atualizado para v3
